Make it work
* Change env variables according to the changes in Supabase to fix the error

Error: getaddrinfo EAI_AGAIN host.supabase.co
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:...) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'host.supabase.co'
}

* Add cors to dependencies and not devDependencies